import { NextRequest, NextResponse } from "next/server";

interface ExportRequest {
  companyName: string;
  recommendation: { label: string; description: string };
  score: number;
  confidenceRange: number;
  memo: {
    thesis: string;
    evidence: string[];
    risks: string[];
    verdict: string;
    diligenceChecklist?: string[];
  } | null;
  categories: Record<string, number>;
  comparables?: {
    cohortLabel: string;
    cohortStats: { sampleSize: number; failureRate: number; survivalRate: number; exitRate: number };
  } | null;
}

export async function POST(request: NextRequest) {
  const body = (await request.json()) as ExportRequest;
  if (!body.companyName?.trim()) {
    return NextResponse.json({ error: "companyName is required" }, { status: 400 });
  }

  const lines: string[] = [];
  lines.push(`# Investment Memo — ${body.companyName}`);
  lines.push(`Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`Recommendation: ${body.recommendation.label}`);
  lines.push(`Score: ${body.score}/100 (+/- ${body.confidenceRange})`);
  lines.push("");
  if (body.memo) {
    lines.push("## Thesis");
    lines.push(body.memo.thesis);
    lines.push("");
    lines.push("## Evidence");
    for (const e of body.memo.evidence) lines.push(`- ${e}`);
    lines.push("");
    lines.push("## Risks");
    for (const r of body.memo.risks) lines.push(`- ${r}`);
    lines.push("");
    if (body.memo.diligenceChecklist && body.memo.diligenceChecklist.length > 0) {
      lines.push("## Diligence Checklist");
      for (const t of body.memo.diligenceChecklist) lines.push(`- [ ] ${t}`);
      lines.push("");
    }
    lines.push("## Verdict");
    lines.push(body.memo.verdict);
    lines.push("");
  }
  lines.push("## Category Scores");
  for (const [k, v] of Object.entries(body.categories)) {
    lines.push(`- ${k}: ${v}/100`);
  }
  lines.push("");
  if (body.comparables) {
    lines.push(`## Cohort Context (${body.comparables.cohortLabel})`);
    lines.push(`- Sample size: ${body.comparables.cohortStats.sampleSize}`);
    lines.push(`- Failure rate: ${Math.round(body.comparables.cohortStats.failureRate * 100)}%`);
    lines.push(`- Survival rate: ${Math.round(body.comparables.cohortStats.survivalRate * 100)}%`);
    lines.push(`- Exit rate: ${Math.round(body.comparables.cohortStats.exitRate * 100)}%`);
    lines.push("");
  }
  lines.push("---");
  lines.push(
    "Disclaimer: This analysis is generated by StartupLens for personal research use only and does not constitute investment advice or a financial promotion.",
  );

  return NextResponse.json({ markdown: `${lines.join("\n")}\n` });
}

